// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBD_JuzHo0kz8tx6tsbC_pOLJOSk3T6Zc',
    appId: '1:18075609650:web:245f3dd38746297bebaa2b',
    messagingSenderId: '18075609650',
    projectId: 'kinetix-8a059',
    authDomain: 'kinetix-8a059.firebaseapp.com',
    storageBucket: 'kinetix-8a059.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiYPhvxXk8Kb7WRWFY4JMXLWMClLXMxoM',
    appId: '1:18075609650:android:896f35d3eb610134ebaa2b',
    messagingSenderId: '18075609650',
    projectId: 'kinetix-8a059',
    storageBucket: 'kinetix-8a059.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ-6Az7wVA0Ie0EJbdusDmuQVnSv2a6n0',
    appId: '1:18075609650:ios:271f26a7477e4c36ebaa2b',
    messagingSenderId: '18075609650',
    projectId: 'kinetix-8a059',
    storageBucket: 'kinetix-8a059.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ-6Az7wVA0Ie0EJbdusDmuQVnSv2a6n0',
    appId: '1:18075609650:ios:271f26a7477e4c36ebaa2b',
    messagingSenderId: '18075609650',
    projectId: 'kinetix-8a059',
    storageBucket: 'kinetix-8a059.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBD_JuzHo0kz8tx6tsbC_pOLJOSk3T6Zc',
    appId: '1:18075609650:web:44e1c1bed1d714c2ebaa2b',
    messagingSenderId: '18075609650',
    projectId: 'kinetix-8a059',
    authDomain: 'kinetix-8a059.firebaseapp.com',
    storageBucket: 'kinetix-8a059.firebasestorage.app',
  );
}
